# Generated by Django 4.2 on 2023-04-23 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DiscussionFacilitator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='trustLevel',
            field=models.CharField(max_length=100),
        ),
    ]
